language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t multi-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true multi-test npm run test -- --coverage

after_success:
  - docker build -t webworkers/multi-client ./client
  - docker build -t webworkers/multi-nginx ./nginx
  - docker build -t webworkers/multi-server ./server
  - docker build -t webworkers/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID"  --password-stdin
  # Take those images and push them to docker hub
  - docker push webworkers/multi-client
  - docker push webworkers/multi-nginx
  - docker push webworkers/multi-server
  - docker push webworkers/multi-worker
